version: "3"
services:
  redis:
    image: redis:alpine
    restart: always

    #volumes:
    #  - ./data/datadir:/data
    #  - ./data/conf/redis.conf:/usr/local/etc/redis/redis.conf
    #  - ./data/logs:/logs
    #command: redis-server /etc/redis/redis.conf # 覆盖容器启动后默认执行的命令
  gorpcx:
    build:
      context: ./
    restart: always
    depends_on:
      - redis
  lb:
    image: dockercloud/haproxy
    links:
      - gorpcx
    ports:
      - "8801:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock